version: '3'

services:
    fincheck-db:
        build: .docker/database
        container_name: fincheck-db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
    fincheck-backend:
        build: .
        container_name: fincheck-backend
        ports:
            - 3000:3000
        command: npm run start:dev
        depends_on:
            - fincheck-db
        volumes:
            - .:/usr/fincheck-backend
volumes:
    postgres_data: