version: '3'

services:
    fincheck-app-backend:
        build: .
        ports:
            - 3000:3000
        volumes:
            - .:/usr/fincheck-app-backend
        command: npm run start:dev
    fincheck-db:
        image: postgres
        restart: always
        volumes:
            - ./.docker/pg-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"